apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yml
- service.yml
images:
- name: app
  newName: ricardoandreh/argocd-poc-app
  newTag: 2969c935ca3ce6fa785e29f773374e901cc89734
